site_name: Leobardo Oscar Alcántara Ocaña
theme:
  name: material
# ---------
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# plugins:
#  - social
#  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leobardooscar
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/joshua_w_d
    - icon: fontawesome/brands/instagram
      link: https://www.linkedin.com/in/willettjames/
    - icon: fontawesome/brands/behance
    - icon: fontawesome/brands/flickr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/leobardooscar"  target="_blank" rel="noopener">Leobardo Óscar Alcántara Ocaña</a>

